SET SQL_SAFE_UPDATES = 0;

UPDATE 1T2023
SET 
    VL_SALDO_INICIAL= REPLACE(VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL= REPLACE(VL_SALDO_FINAL, ',', '.'),
    DIA = REPLACE(DIA, '/', '-')
WHERE DIA IS NOT NULL;

UPDATE 2T2023
SET 
    VL_SALDO_INICIAL= REPLACE(VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL= REPLACE(VL_SALDO_FINAL, ',', '.'),
    DIA = REPLACE(DIA, '/', '-')
WHERE DIA IS NOT NULL;

UPDATE 3T2023
SET 
    VL_SALDO_INICIAL= REPLACE(VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL= REPLACE(VL_SALDO_FINAL, ',', '.'),
    DIA = REPLACE(DIA, '/', '-')
WHERE DIA IS NOT NULL;

UPDATE 4T2023
SET 
    VL_SALDO_INICIAL= REPLACE(VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL= REPLACE(VL_SALDO_FINAL, ',', '.'),
    DIA = REPLACE(DIA, '/', '-')
WHERE DIA IS NOT NULL;

UPDATE 1T2024
SET 
    VL_SALDO_INICIAL= REPLACE(VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL= REPLACE(VL_SALDO_FINAL, ',', '.'),
    DIA = REPLACE(DIA, '/', '-')
WHERE DIA IS NOT NULL;

UPDATE 2T2024
SET 
    VL_SALDO_INICIAL= REPLACE(VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL= REPLACE(VL_SALDO_FINAL, ',', '.'),
    DIA = REPLACE(DIA, '/', '-')
WHERE DIA IS NOT NULL;

UPDATE 3T2024
SET 
    VL_SALDO_INICIAL= REPLACE(VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL= REPLACE(VL_SALDO_FINAL, ',', '.'),
    DIA = REPLACE(DIA, '/', '-')
WHERE DIA IS NOT NULL;

UPDATE 4T2024
SET 
    VL_SALDO_INICIAL= REPLACE(VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL= REPLACE(VL_SALDO_FINAL, ',', '.'),
    DIA = REPLACE(DIA, '/', '-')
WHERE DIA IS NOT NULL;

SET SQL_SAFE_UPDATES = 1;

ALTER TABLE 1T2023
MODIFY COLUMN VL_SALDO_INICIAL DECIMAL(20,2),
MODIFY COLUMN VL_SALDO_FINAL DECIMAL(20,2),
MODIFY COLUMN DIA DATE;

ALTER TABLE 2T2023
MODIFY COLUMN VL_SALDO_INICIAL DECIMAL(20,2),
MODIFY COLUMN VL_SALDO_FINAL DECIMAL(20,2),
MODIFY COLUMN DIA DATE;

ALTER TABLE 3T2023
MODIFY COLUMN VL_SALDO_INICIAL DECIMAL(20,2),
MODIFY COLUMN VL_SALDO_FINAL DECIMAL(20,2),
MODIFY COLUMN DIA DATE;

ALTER TABLE 4T2023
MODIFY COLUMN VL_SALDO_INICIAL DECIMAL(20,2),
MODIFY COLUMN VL_SALDO_FINAL DECIMAL(20,2),
MODIFY COLUMN DIA DATE;

ALTER TABLE 1T2024
MODIFY COLUMN VL_SALDO_INICIAL DECIMAL(20,2),
MODIFY COLUMN VL_SALDO_FINAL DECIMAL(20,2),
MODIFY COLUMN DIA DATE;

ALTER TABLE 2T2024
MODIFY COLUMN VL_SALDO_INICIAL DECIMAL(20,2),
MODIFY COLUMN VL_SALDO_FINAL DECIMAL(20,2),
MODIFY COLUMN DIA DATE;

ALTER TABLE 3T2024
MODIFY COLUMN VL_SALDO_INICIAL DECIMAL(20,2),
MODIFY COLUMN VL_SALDO_FINAL DECIMAL(20,2),
MODIFY COLUMN DIA DATE;

ALTER TABLE 4T2024
MODIFY COLUMN VL_SALDO_INICIAL DECIMAL(20,2),
MODIFY COLUMN VL_SALDO_FINAL DECIMAL(20,2),
MODIFY COLUMN DIA DATE;