SELECT rc.*, temp.DESPESAS

-- Ultimo Semestre
FROM rel_cadop rc
JOIN (
    SELECT REG_ANS, (VL_SALDO_FINAL - VL_SALDO_INICIAL) AS DESPESAS
    FROM 4T2024
    WHERE UPPER(DESCRICAO) LIKE "%EVENTOS%SINISTROS%CONHECIDOS%OU%AVISADOS%DE%ASSISTÊNCIA%A%SAÚDE%MEDICO%HOSPITALAR%"
) temp
ON rc.Registro_ANS = temp.REG_ANS
ORDER BY temp.CALCULO ASC
LIMIT 10;


-- Ultimo ano
SELECT rc.*, temp.CALCULO
FROM rel_cadop rc
JOIN (
    SELECT REG_ANS, (VL_SALDO_FINAL - VL_SALDO_INICIAL) AS CALCULO
    FROM (
        SELECT REG_ANS, VL_SALDO_FINAL, VL_SALDO_INICIAL, DESCRICAO
        FROM 1T2024
        UNION ALL
        SELECT REG_ANS, VL_SALDO_FINAL, VL_SALDO_INICIAL, DESCRICAO
        FROM 2T2024
        UNION ALL
        SELECT REG_ANS, VL_SALDO_FINAL, VL_SALDO_INICIAL, DESCRICAO
        FROM 3T2024
        UNION ALL
        SELECT REG_ANS, VL_SALDO_FINAL, VL_SALDO_INICIAL, DESCRICAO
        FROM 4T2024
    ) as combined
    WHERE UPPER(DESCRICAO) LIKE "%EVENTOS%SINISTROS%CONHECIDOS%OU%AVISADOS%DE%ASSISTÊNCIA%A%SAÚDE%MEDICO%HOSPITALAR%"
) temp
ON rc.Registro_ANS = temp.REG_ANS
ORDER BY temp.CALCULO ASC
LIMIT 10;
