CREATE TABLE rel_Cadop (
	Registro_ANS INT,
    CNPJ VARCHAR(14),
    Razao_Social VARCHAR(255),
    Nome_Fantasia VARCHAR(255),
    Modalidade VARCHAR(255),
    Logradouro VARCHAR(255),
    Numero VARCHAR(65),
    Complemento VARCHAR(127),
    Bairro VARCHAR(127),
    Cidade VARCHAR(127),
    UF CHAR(2),
	CEP VARCHAR(8),
    DDD VARCHAR(5),
    Telefone VARCHAR(65),
    Fax VARCHAR(65),
    Endereco_eletronico VARCHAR(127),
    Representante VARCHAR(127),
    Cargo_Representante VARCHAR(127),
    Regiao_de_Comercializacao VARCHAR(2),
    DIA_Registro_ANS DATE,
    PRIMARY KEY (Registro_ANS)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE 1T2023(
	ID INT AUTO_INCREMENT,
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20),
    PRIMARY KEY (ID)
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE 2T2023(
	ID INT AUTO_INCREMENT,
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20),
    PRIMARY KEY (ID)
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE 3T2023(
    ID INT AUTO_INCREMENT,
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20),
    PRIMARY KEY (ID)
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE 4T2023(
    ID INT AUTO_INCREMENT,
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20),
    PRIMARY KEY (ID)
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE 1T2024(
    ID INT AUTO_INCREMENT,
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20),
    PRIMARY KEY (ID)
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE 2T2024(
    ID INT AUTO_INCREMENT,
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20),
    PRIMARY KEY (ID)
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE 3T2024(
    ID INT AUTO_INCREMENT,
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20),
    PRIMARY KEY (ID)
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE 4T2024(
    ID INT AUTO_INCREMENT,
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20),
    PRIMARY KEY (ID)
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

SET GLOBAL connect_timeout = 240; 

LOAD DATA INFILE 'CSVs/Relatorio_cadop.csv'
INTO TABLE rel_Cadop
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(Registro_ANS, CNPJ, Razao_Social, Nome_Fantasia, Modalidade, Logradouro, Numero, Complemento, Bairro, Cidade, UF, CEP, DDD, Telefone, Fax, Endereco_eletronico, Representante, Cargo_Representante, Regiao_de_Comercializacao, DIA_Registro_ANS);

SET SQL_SAFE_UPDATES = 0;

CREATE TEMPORARY TABLE temp_1T2023 (
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

LOAD DATA INFILE 'CSVs/1T2023.csv'
INTO TABLE temp_1T2023
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);

INSERT INTO 1T2023 (DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT t.DIA, t.REG_ANS, t.CD_CONTA_CONTABIL, t.DESCRICAO, t.VL_SALDO_INICIAL, t.VL_SALDO_FINAL
FROM temp_1T2023 t
WHERE t.REG_ANS IN (SELECT Registro_ANS FROM rel_Cadop);

DROP TEMPORARY TABLE temp_1T2023;

CREATE TEMPORARY TABLE temp_2T2023 (
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

LOAD DATA INFILE 'CSVs/2T2023.csv'
INTO TABLE temp_2T2023
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);

INSERT INTO 2T2023 (DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT t.DIA, t.REG_ANS, t.CD_CONTA_CONTABIL, t.DESCRICAO, t.VL_SALDO_INICIAL, t.VL_SALDO_FINAL
FROM temp_2T2023 t
WHERE t.REG_ANS IN (SELECT Registro_ANS FROM rel_Cadop);

DROP TEMPORARY TABLE temp_2T2023;

CREATE TEMPORARY TABLE temp_3T2023 (
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

LOAD DATA INFILE 'CSVs/3T2023.csv'
INTO TABLE temp_3T2023
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);

INSERT INTO 3T2023 (DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT t.DIA, t.REG_ANS, t.CD_CONTA_CONTABIL, t.DESCRICAO, t.VL_SALDO_INICIAL, t.VL_SALDO_FINAL
FROM temp_3T2023 t
WHERE t.REG_ANS IN (SELECT Registro_ANS FROM rel_Cadop);

DROP TEMPORARY TABLE temp_3T2023;

CREATE TEMPORARY TABLE temp_4T2023 (
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

LOAD DATA INFILE 'CSVs/4T2023.csv'
INTO TABLE temp_4T2023
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);

INSERT INTO 4T2023 (DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT t.DIA, t.REG_ANS, t.CD_CONTA_CONTABIL, t.DESCRICAO, t.VL_SALDO_INICIAL, t.VL_SALDO_FINAL
FROM temp_4T2023 t
WHERE t.REG_ANS IN (SELECT Registro_ANS FROM rel_Cadop);

DROP TEMPORARY TABLE temp_4T2023;

CREATE TEMPORARY TABLE temp_1T2024 (
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

LOAD DATA INFILE 'CSVs/1T2024.csv'
INTO TABLE temp_1T2024
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);

INSERT INTO 1T2024 (DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT t.DIA, t.REG_ANS, t.CD_CONTA_CONTABIL, t.DESCRICAO, t.VL_SALDO_INICIAL, t.VL_SALDO_FINAL
FROM temp_1T2024 t
WHERE t.REG_ANS IN (SELECT Registro_ANS FROM rel_Cadop);

DROP TEMPORARY TABLE temp_1T2024;

CREATE TEMPORARY TABLE temp_2T2024 (
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

LOAD DATA INFILE 'CSVs/2T2024.csv'
INTO TABLE temp_2T2024
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);

INSERT INTO 2T2024 (DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT t.DIA, t.REG_ANS, t.CD_CONTA_CONTABIL, t.DESCRICAO, t.VL_SALDO_INICIAL, t.VL_SALDO_FINAL
FROM temp_2T2024 t
WHERE t.REG_ANS IN (SELECT Registro_ANS FROM rel_Cadop);

DROP TEMPORARY TABLE temp_2T2024;

CREATE TEMPORARY TABLE temp_3T2024 (
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

LOAD DATA INFILE 'CSVs/3T2024.csv'
INTO TABLE temp_3T2024
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);

INSERT INTO 3T2024 (DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT t.DIA, t.REG_ANS, t.CD_CONTA_CONTABIL, t.DESCRICAO, t.VL_SALDO_INICIAL, t.VL_SALDO_FINAL
FROM temp_3T2024 t
WHERE t.REG_ANS IN (SELECT Registro_ANS FROM rel_Cadop);

DROP TEMPORARY TABLE temp_3T2024;

CREATE TEMPORARY TABLE temp_4T2024 (
    DIA VARCHAR(10),
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL VARCHAR(20),
    VL_SALDO_FINAL VARCHAR(20)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

LOAD DATA INFILE 'CSVs/4T2024.csv'
INTO TABLE temp_4T2024
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);

INSERT INTO 4T2024 (DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT t.DIA, t.REG_ANS, t.CD_CONTA_CONTABIL, t.DESCRICAO, t.VL_SALDO_INICIAL, t.VL_SALDO_FINAL
FROM temp_4T2024 t
WHERE t.REG_ANS IN (SELECT Registro_ANS FROM rel_Cadop);
DROP TEMPORARY TABLE temp_4T2024;

SET SQL_SAFE_UPDATES = 1;